services:
  - type: worker
    name: SaveRestrictedContentBot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    disk:
      name: bot-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: AUTH
        sync: false
      - key: FORCESUB
        sync: false
      - key: DATA_DIR
        value: /data
